### ISSUE TITLE
changing twitter logo to X

### ISSUE THREAD

**Issue by Ketanop321** [divyansh-2005/FinNews#105]
Update the old twitter logo to X
Also add hover effects on social icons and enhance footer
**screenshots  x***
![image](https://github.com/user-attachments/assets/e5a33778-6275-45c6-ab93-a62746e99f86)

**check list**
- [✅ ] I am contributing under GSSoC-ext
- [✅ ] I am contributing under hacktoberfest
- [✅ ] I follow contribution guidlines

**Comment by ArthKulkarni93** [comment]
I'd love to work on this issue, I'll get it done by tomorrow itself. 
I've previously worked on such issues under GSSOC

**Comment by Ketanop321** [comment]
@divyansh-2005 can you check this issue please?

**Comment by rishi998** [comment]
@divyansh-2005 I would like to work on this issue under gssoc-ext. Kindly assign me this issue and put necessary labels and levels to this issue.

**Comment by Gamerking177** [comment]
@rishi998 bro pls find ad raise ur own issue

**Comment by Gamerking177** [comment]
@rishi998 pls dont do begging in every issue

**Comment by sambangiadharsh** [comment]
Could I have your permission to work on fixing these issues? I believe it will be a great learning experience for me, and I’m confident that I can make valuable improvements.
