### ISSUE TITLE
[FEATURE] Back to Top button 

### ISSUE THREAD

**Issue by Sawan-Kushwah** [divyansh-2005/FinNews#110]
There should be a button back to top if user get scroll to down 
create a better user experience
**check list**
- [✔️ ] I am contributing under GSSoC-ext
- [ ✔️] I am contributing under hacktoberfest
- [ ✔️] I follow contribution guidlines

**Comment by lakshay2425** [comment]
@DiwareNamrata23 @divyansh-2005 I would like to work on this issue. Please assign me.

**Comment by DiwareNamrata23** [comment]
@lakshay2425 go ahead
