### ISSUE TITLE
Daily news letter section not responsive and overflow to footer as well

### ISSUE THREAD

**Issue by Sureshwebdeveloper** [divyansh-2005/FinNews#16]
Daily news letter section not responsive and overflow to footer as we'll

![Screenshot_2024-10-02-10-43-51-311_com android chrome](https://github.com/user-attachments/assets/9afa5239-c2e9-427b-9b1d-f1ee67d806e5)
![Screenshot_2024-10-02-10-43-58-319_com android chrome](https://github.com/user-attachments/assets/3e24e695-cbaf-4865-b6a7-2f9cea60fd90)

If you assign to me I will fix it and add a label the gssocext and hactoberfest badges and add a level as we'll.
@divyansh-2005

**Comment by divyansh-2005** [comment]
we need a resign of this section

**Comment by Sureshwebdeveloper** [comment]
If need redesign assign to me
