### ISSUE TITLE
Create a landing page for signup and login functionality.

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [divyansh-2005/FinNews#2]
Currently the signup and login links dont work.
Please assign the issue to me under GSSOC'24.

**Comment by princekumar39** [comment]
@divyansh-2005 
 i want to write the **backend code of this signin/signup page** . Please assigned it to me .
 I can write the backend code .

**Comment by Tanish0023** [comment]
I will be able to help you with this I have prior experience and can help you with the signin and signup pages

**Comment by divyansh-2005** [comment]
@princekumar39 create new issue
