### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lakshay2425** [divyansh-2005/FinNews#27]
**Describe the bug**
When the user visits the My Feed page on the website, website doesn't have a button which allow user to navigate back to the Home page of the website.

**To Reproduce**
1. Go to 'My Feed Page after clicking the My Feed on the navbar'
2. Click on 'Fin News in the Navbar'
3. It doesn't navigate back to the home page of the website.

**Expected behavior**
When the user clicks on the Fin News after the user has opened the My Feed Page. It should navigate to the Home Page of the website. 

**Screenshots before**
![image](https://github.com/user-attachments/assets/0d1b2c2c-a0cc-4de2-bc12-59d19d3c5a73)

**screenshots after fix***

**check list**
- [Yes ] I am contributing under GSSoC-ext
- [ Yes] I am contributing under hacktoberfest
- [ Yes] I follow contribution guidlines

**Additional context**
After fixing this bug, it will allow user to easily navigate on the website.

**Comment by lakshay2425** [comment]
I want to fix this issue.

**Comment by divyansh-2005** [comment]
plz add title to issue
