### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Virenishere** [divyansh-2005/FinNews#29]
Title: Missing Home Page Navigation

Description:
There is no direct navigation option to return to the home page from various sections of the FIN NEWS website. This can lead to a poor user experience as users may find it difficult to return to the main page after navigating to subpages.

Steps to Reproduce:

Go to any subpage (e.g., a news article or a category section).
Look for a link or button that navigates back to the home page.
Observe that there is no "Home" button or logo link directing users back to the home page.
Expected Behavior:
There should be a clearly visible home page navigation option, either in the form of a "Home" button in the header or making the logo clickable to return to the home page.

Actual Behavior:
There is no visible way to return to the home page, requiring users to manually edit the URL or rely on browser back buttons.

I will fix this issue and Could you please assign this issue to me under GSSOC'24 extd?

**Comment by lakshay2425** [comment]
This bug has already been fixed.  @Virenishere

**Comment by Virenishere** [comment]
Alright I understood and please check my feature request prompt

**Comment by lakshay2425** [comment]
I'm not the project admin. @divyansh-2005 is the project admin.

**Comment by Virenishere** [comment]
Thank you for letting me know @lakshay2425
