### ISSUE TITLE
Design About us and Contact us pages 

### ISSUE THREAD

**Issue by Vaibhav-Kumar-K-R** [divyansh-2005/FinNews#3]
Currently in the footer section the link to about and contact sections dont work.
Please assign the issue to me under GSSOC'24

**Comment by RohitChoukiker** [comment]
I have noticed that the links to the About and Contact sections in the footer are not working.
 Could you please assign it to me?

**Comment by Charul00** [comment]
can u pleas assign to me

**Comment by taansssss** [comment]
Please assign the issue to me under GSSOC'24

**Comment by SumitSahu44** [comment]
hey @divyansh-2005 can you assign this to me , i can do it with best quality or within 1-2 days so please assign me
