### ISSUE TITLE
Enhancement of the blogs section

### ISSUE THREAD

**Issue by MetiUmashri** [divyansh-2005/FinNews#36]
There are quite big headings in the blog page this doesn't give good effect on the website. A proper styling would beautify this page.

<img width="960" alt="image" src="https://github.com/user-attachments/assets/7aeb0601-a316-4ba2-a458-b627445ed640">

**check list**
- [ .] I am contributing under GSSoC-ext
- [ ] I am contributing under hacktoberfest
- [ .] I follow contribution guidlines
kindly assign this issue to me

**Comment by MetiUmashri** [comment]
@divyansh-2005 @DiwareNamrata23 I want to implement this functionality/feature on the website.

**Comment by taansssss** [comment]
please assign this issue to me
@MetiUmashri

**Comment by SuyashSingh01** [comment]
Hi @divyansh-2005  the Depolyment link is not working bcoz of one of the bug  in Blogsection and Sectionheading  .Please assign this to me .I'm Interested to contribute.  
![image](https://github.com/user-attachments/assets/12a36aff-40cd-4fb4-945a-71712eaa023a)
