### ISSUE TITLE
[BUG]: Navbar Sections like(News, Schemes and Newsletter) Not Responding!

### ISSUE THREAD

**Issue by SCR01** [divyansh-2005/FinNews#38]
#### Describe the bug:
The **Newsletter**, **Schemes**, and **News** sections in the navigation bar are not responding when clicked.

#### To Reproduce:
1. Go to the website's homepage.
2. Click on the 'Newsletter' link in the navigation bar.
3. Click on the 'Schemes' or 'News' sections.
4. Notice that none of these sections are responsive to clicks.

#### Expected behavior:
When clicking on the **Newsletter**, **Schemes**, or **News** links, the user should be redirected to the respective pages or sections.

#### Video:

https://github.com/user-attachments/assets/d08b4cab-74d3-435b-935e-c392768c49e4

#### Checklist:
- [✔️] I am contributing under GSSoC-ext
- [✔️] I am contributing under Hacktoberfest
- [✔️ ] I follow the contribution guidelines

#### Additional context:
This bug affects navigation, making it difficult for users to access important sections like **Newsletter**, **Schemes**, and **News**.

**Comment by divyansh-2005** [comment]
we need to make pages first

**Comment by SCR01** [comment]
I will make it
