### ISSUE TITLE
[BUG]:  TypeError in My Feed Section Displaying 'Our Feed' Instead of Personalized Feed!

### ISSUE THREAD

**Issue by SCR01** [divyansh-2005/FinNews#40]
### **Describe the bug**
A **TypeError** occurs in the **My Feed** section, causing it to display 'Our Feed' and random topics instead of personalized content. The expected behavior is to display user-specific news or topics based on preferences.

### **To Reproduce**
1. Go to the **My Feed** section.
2. Observe the title displaying **'Our Feed'** instead of **'My Feed'**.
3. Random topics are shown, rather than personalized content.
4. A **TypeError** is encountered.

### **Expected behavior**
The **My Feed** section should show the personalized feed with relevant topics based on the user's preferences, and the title should read **'My Feed'** instead of **' Our Feed'**.

### **Error Logs**
(If available, provide the TypeError message here.)

### **Screenshots**
Before Fix:
- Title: **'Our Feed'**
- Random topics unrelated to user preferences are displayed.

![typeError](https://github.com/user-attachments/assets/c91a6e77-89a1-41ca-8158-b770256f526b)

After Fix (Expected):
- Title: **'My Feed'**
- Personalized content based on the user's choices is shown.

### **Checklist**
- [✔️ ] I am contributing under GSSoC-ext
- [✔️ ] I am contributing under Hacktoberfest
- [✔️] I follow contribution guidelines

### **Additional context**
This issue might be due to incorrect data mapping or a bug in the algorithm fetching user-specific data for the feed. The **TypeError** suggests a handling problem in fetching or processing personalized content. The fix should involve ensuring the correct mapping of user preferences to the feed content.

**Comment by divyansh-2005** [comment]
very minor change can't be assigned
