### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by SCR01** [divyansh-2005/FinNews#41]
### **Is your feature request related to a problem? Please describe.**
Currently, users can only consume content passively, but there's no way to gather their opinions or feedback. This limits user engagement and interactivity on the platform.

### **Describe the solution you'd like**
Add a **Polls and Surveys** section that allows users to participate in quick polls or fill out surveys on financial topics, market trends, or their opinions on certain articles.

### **Screenshots**
![Screenshot 2024-10-03 020956](https://github.com/user-attachments/assets/fbe67e83-6d55-4835-8309-3d95bf7f3dc0)

### **Checklist**
- [✔️] I am contributing under GSSoC-ext
- [✔️] I am contributing under Hacktoberfest
- [✔️] I follow contribution guidelines

**Comment by divyansh-2005** [comment]
not needed
