### ISSUE TITLE
[FEATURE]: Update the footer

### ISSUE THREAD

**Issue by NK-Works** [divyansh-2005/FinNews#44]
![image](https://github.com/user-attachments/assets/0594c267-c7b5-4888-a873-85395f8f0d33)
i can make the footer better...
make sure to add the logos...
thanks:)

**Comment by BarryByte** [comment]
Hey @divyansh-2005 I would love to work on this issue, please assign this issue to me. Thanks.

**Comment by SuyashSingh01** [comment]
@divyansh-2005  hi ,I'm Interested  to contribute  . please assign this to me.
