### ISSUE TITLE
[FEATURE] :IMPROVE THE COLOR CODE AND UI OF NAVBAR

### ISSUE THREAD

**Issue by laxmanp090404** [divyansh-2005/FinNews#50]
#### **Is your feature request related to a problem? Please describe.**
Currently, the navbar appears to have a bland and outdated color scheme, which does not align with the modern aesthetic standards of the website. I'm often frustrated by how the current color code lacks contrast and appeal, making navigation less intuitive for users. Additionally, the layout and design could be more user-friendly, particularly when viewed on different screen sizes.

#### **Describe the solution you'd like**
I would like to suggest an improvement to the color palette used in the navbar, opting for a modern and visually appealing scheme that enhances readability and complements the rest of the site’s design. The UI should also be updated to include better spacing, clearer typography, and mobile responsiveness. Ensuring that the navbar provides a seamless experience across various devices is crucial. An ideal solution would also involve subtle animations to improve interaction feedback.

#### **Checklist**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under Hacktoberfest
- [x] I follow the contribution guidelines

**Comment by Zish303** [comment]
Hi, I want to solve this issue for Hacktoberfest and GSSoC. Please assign this issue to me.
