### ISSUE TITLE
[FEATURE] highlighting buttons present in navigation bar

### ISSUE THREAD

**Issue by KunalPusdekar** [divyansh-2005/FinNews#52]
**Is your feature request related to a problem? Please describe.**
 highlighting buttons present in navigation bar 

**Describe the solution you'd like**
 highlighting buttons present in navigation bar

**Screenshots**

**screenshots/video of feature**

**check list** 
- [x ] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Comment by nabanichowdhury** [comment]
@KunalPusdekar I would like to highlight the buttons present in the navigation bar when I am being directed to that specific route.

Can you assign this issue to me?
