### ISSUE TITLE
Add content to website

### ISSUE THREAD

**Issue by divyansh-2005** [divyansh-2005/FinNews#6]
**Is your feature request related to a problem? Please describe.**
Currently FinNews has random text change it to legit news content 

**Describe the solution you'd like**
change the content to finance News 

**Screenshots**

**Additional context**

**Comment by charliehustlr1792** [comment]
I'm willing to fix this issue. Can you pls assign this to me?also pls add hacktoberfest and gssoc labels

**Comment by Amarjha01** [comment]
Hello! divyansh sir, could you please assign this to me please.

**Comment by vishesh1525** [comment]
@divyansh-2005  Hloo sir i am also willing to contribute towards to this can you assign this issue to me

**Comment by divyansh-2005** [comment]
do this ASAP

**Comment by divyansh-2005** [comment]
@Amarjha01 fetch live news

**Comment by Amarjha01** [comment]
> @Amarjha01 fetch live news

okay sir,

  
@charliehustlr1792  brother please join  My [discord](https://discord.com/invite/eTtqF6mb) server for information sharing and lets finish this by tomorrow evening.

**Comment by charliehustlr1792** [comment]
It is showing Invite Invalid! I'm also eager to finish this one asap

**Comment by Amarjha01** [comment]
https://discord.com/invite/vnrX9Ud9

**Comment by Amarjha01** [comment]
https://discord.com/invite/eTtqF6mb

**Comment by Amarjha01** [comment]
@divyansh-2005 sir currently i'm using mine APIkey to fetch data later you can change it or I'll give you mine.

**Comment by Amarjha01** [comment]
@divyansh-2005 air can I use tailwind css ? Needs some adjustment in display images.

**Comment by Amarjha01** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/27c6c190-b73f-4cf8-9961-2ae88dd10f8a">

i faced some chalanges while fetching data because most of the API are paid or only few are free but with limitation to no. of request per day.  in spite of challenges 25% is completed

**Comment by Amarjha01** [comment]
<img width="956" alt="image" src="https://github.com/user-attachments/assets/779e7488-bc9c-4d75-825d-182c43a9e0a7">
50% completed

@divyansh-2005 sir please verify it .

**Comment by Amarjha01** [comment]
@charliehustlr1792  brother where are you ?

**Comment by charliehustlr1792** [comment]
Reply on discord

**Comment by charliehustlr1792** [comment]
@Amarjha01 reply

**Comment by Amarjha01** [comment]
@divyansh-2005  can you please change the level from level 2 to level2 or level3 because point is not added in leaderboard.

<img width="802" alt="image" src="https://github.com/user-attachments/assets/96705e2f-eb75-472b-b54a-d42393be94f7">
