### ISSUE TITLE
[FEATURE] Improvement in ui of my feed page

### ISSUE THREAD

**Issue by Sawan-Kushwah** [divyansh-2005/FinNews#61]
**Is your feature request related to a problem? Please describe.**
As you can see in image it not looking professional

![image](https://github.com/user-attachments/assets/6e7f464a-c76c-4baa-8cd9-5e58c80cda4a)

**check list**
- [✔️ ] I am contributing under GSSoC-ext
- [ [✔️ ] I am contributing under hacktoberfest
- [[✔️  ] I follow contribution guidlines

**Comment by Sawan-Kushwah** [comment]
Please assign me i want to work on this issue with corresponding level tags

**Comment by Sawan-Kushwah** [comment]
https://github.com/user-attachments/assets/b9949810-0e33-4b8d-932b-9a51879931ba

have a look on it 
See this if any changes required please tell me i am ready to do !
else can i make pr of it?

**Comment by divyansh-2005** [comment]
raise pr
