### ISSUE TITLE
[BUG]:Double footer issue

### ISSUE THREAD

**Issue by laxmanp090404** [divyansh-2005/FinNews#65]
**Describe the bug**  
There are two footers appearing on the page, which is redundant and impacts the overall UI.

**To Reproduce**  
1. Go to the homepage or any page with the footer.
2. Scroll down to the bottom of the page.
3. Observe the presence of two identical footers.
4. See the duplication error.

**Expected behavior**  
Only one footer should appear at the bottom of the page to avoid redundancy and improve the user experience.

**Screenshots before**  
![image](https://github.com/user-attachments/assets/1760782b-253c-475e-9fa7-98f557864eea)

**Check list**
- [x] I am contributing under GSSoC-ext.
- [x] I am contributing under Hacktoberfest.
- [x] I follow the contribution guidelines.

**Additional context**  
This issue might be caused by rendering the footer component multiple times or duplicating the code for the footer in the layout structure. Please review the page layout and component logic.

**Comment by priyanshuverma-dev** [comment]
@laxmanp090404  I would Like to work on this issue

**Comment by 4F24L** [comment]
can I work on this?
