### ISSUE TITLE
[FEATURE]: Create an Above section and testimonial section

### ISSUE THREAD

**Issue by laxmanp090404** [divyansh-2005/FinNews#66]
**Is your feature request related to a problem? Please describe.**  
Currently, there is no dedicated section for showcasing key information and testimonials from users. This makes it challenging for potential users to understand the value of the application and to see feedback from existing users.

**Describe the solution you'd like**  
I would like to create an "Above" section that highlights key features or announcements and a "Testimonials" section to display user feedback and reviews. This will help improve user engagement and provide social proof of the application’s effectiveness.

**Screenshot (Not the exact design similar to this):**
![image](https://github.com/user-attachments/assets/9e63aff3-0a83-4e7e-97b2-e4a34e37f210)

**Check list**
- [x] I am contributing under GSSoC-ext.
- [x] I am contributing under Hacktoberfest.
- [x] I follow the contribution guidelines.

**Comment by laxmanp090404** [comment]
please assign me this issue @divyansh-2005

**Comment by divyansh-2005** [comment]
this is not needed now
