### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by NK-Works** [divyansh-2005/FinNews#69]
I want to add the contributing.md for this project.

**Comment by AnujSaha0111** [comment]
I want to work on it. Can you please assign it to me?
can you please add gssoc-ext label

**Comment by NK-Works** [comment]
@divyansh-2005 just to be clear do you want some specific requirements for the contributing.md
e.g. 
- a person can only create 2 issues max simultaneously.
- pull req must have screenshots of the updates.
instructions like these...
