### ISSUE TITLE
[FEATURE] : There should be back button on the specific blog reading page. It would be a good User Experience

### ISSUE THREAD

**Issue by VinayLodhi1712** [divyansh-2005/FinNews#74]
**Is your feature request related to a problem? Please describe.**
 I'm always frustrated when there is no back button on pages and we need to back from the chrome back button or tapping on home page button

**Describe the solution you'd like**
adding a back button on blogs so user can navigate to other blogs easily through main blog page 

**Screenshots**
![Uploading back.png…]()

**screenshots/video of feature**

**check list**
- [ 1] I am contributing under GSSoC-ext
- [1 ] I am contributing under hacktoberfest
- [1 ] I follow contribution guidlines

plz add level so i start working on it

**Comment by Swetabh333** [comment]
I'd like to work on this

**Comment by divyansh-2005** [comment]
add back button on every page
