### ISSUE TITLE
[FEATURE] Adding a newsletter section in the footer

### ISSUE THREAD

**Issue by Aazib-at-hub** [divyansh-2005/FinNews#87]
**Is your feature request related to a problem? Please describe.**

**Adding a Newsletter section in the footer**
It will to communicate with the people, promote your brands & blogs.

**Screenshots**

**screenshots/video of feature**

**check list**
- [ yes ] I am contributing under GSSoC-ext
- [ yes ] I am contributing under hacktoberfest
- [ yes ] I follow contribution guidlines

**Comment by BarryByte** [comment]
@divyansh-2005 I would to work on this issue, please assign this issue to me. Thanks.

**Comment by Aazib-at-hub** [comment]
@Sourabh782 @Amarjha01 can you assign it to me?

**Comment by Aazib-at-hub** [comment]
@divyansh-2005 should i start working?... you have forgot to assign i think so.
