### ISSUE TITLE
[BUG] Double footer on landing page

### ISSUE THREAD

**Issue by 4F24L** [divyansh-2005/FinNews#89]
**Describe the bug**
There are two footer sections available in the landing page. which is not appropriate.

**Screenshots before**
![image](https://github.com/user-attachments/assets/94a42a0d-6499-4172-9a52-8ee6a8041c67)

**screenshots after fix***

**check list**
- [x] I am contributing under GSSoC-ext
- [x] I am contributing under hacktoberfest
- [x] I follow contribution guidlines

**Additional context**

**Comment by BarryByte** [comment]
@divyansh-2005 I would to work on this issue, please assign this issue to me. Thanks.

**Comment by DiwareNamrata23** [comment]
@4F24L already it is solved you can raise new issue
